name: autoWEditor
main: autoWEditor\autoWEditor
version: 2.0
api:
- 1.0
- 2.0.0
- 3.0.0
commands:
 ///e:
  description: 
  usage: "////e"
 ///copy:
  description: 
  usage: "////copy"
 t:
  description: 
  usage: "/t"



